# Generated by Django 3.2.25 on 2024-05-03 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
                ),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='修改者'),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='token')),
                ('begin_time', models.DateTimeField(verbose_name='有效期开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='有效期结束时间')),
                ('desc', models.CharField(default='', max_length=1000, verbose_name='描述')),
            ],
            options={
                'verbose_name': '凭证',
                'verbose_name_plural': '凭证',
            },
        ),
        migrations.CreateModel(
            name='CredentialResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
                ),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='修改者'),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('resource_type', models.CharField(max_length=32, verbose_name='资源类型')),
                ('filter_condition', models.JSONField(default=dict, verbose_name='关联范围')),
                (
                    'credential',
                    models.ForeignKey(
                        db_constraint=False,
                        help_text='凭证',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credential_set',
                        to='credential.credential',
                    ),
                ),
            ],
            options={
                'verbose_name': '凭证关联的资源',
                'verbose_name_plural': '凭证关联的资源',
            },
        ),
    ]
