# Generated by Django 4.2.13 on 2024-05-28 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.CharField(db_index=True, default="", max_length=32, null=True, verbose_name="创建者"),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("username", models.CharField(blank=True, max_length=32, null=True, verbose_name="登录用户名")),
                ("ip", models.CharField(blank=True, max_length=32, null=True, verbose_name="登录ip")),
                ("agent", models.TextField(blank=True, null=True, verbose_name="agent信息")),
                ("browser", models.CharField(blank=True, max_length=255, null=True, verbose_name="浏览器名")),
                (
                    "os",
                    models.CharField(
                        blank=True, help_text="操作系统", max_length=255, null=True, verbose_name="操作系统"
                    ),
                ),
                ("continent", models.CharField(blank=True, max_length=64, null=True, verbose_name="州")),
                ("country", models.CharField(blank=True, max_length=64, null=True, verbose_name="国家")),
                ("province", models.CharField(blank=True, max_length=64, null=True, verbose_name="省份")),
                ("city", models.CharField(blank=True, max_length=64, null=True, verbose_name="城市")),
                ("district", models.CharField(blank=True, max_length=64, null=True, verbose_name="县区")),
                ("isp", models.CharField(blank=True, max_length=64, null=True, verbose_name="运营商")),
                ("area_code", models.CharField(blank=True, max_length=64, null=True, verbose_name="区域代码")),
                ("country_english", models.CharField(blank=True, max_length=64, null=True, verbose_name="英文全称")),
                ("country_code", models.CharField(blank=True, max_length=64, null=True, verbose_name="简称")),
                ("longitude", models.CharField(blank=True, max_length=64, null=True, verbose_name="经度")),
                ("latitude", models.CharField(blank=True, max_length=64, null=True, verbose_name="纬度")),
                (
                    "login_type",
                    models.CharField(
                        choices=[("NORMAL", "普通登录"), ("WECHAT_SCAN_CODE", "微信扫码登录")],
                        default="NORMAL",
                        max_length=32,
                        verbose_name="登录类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
            },
        ),
    ]
