"""
Django settings for apps project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os

import environ

# 读取环境变量文件
# 配置优先级 环境变量 -> .env文件 -> settings.py
environ.Env.read_env()

ENVIRONMENT = os.getenv("ENVIRONMENT", "dev")
DJANGO_CONF_MODULE = "config.{env}".format(env=ENVIRONMENT)
try:
    _module = __import__(DJANGO_CONF_MODULE, globals(), locals(), ["*"])
except ImportError as e:
    raise ImportError("Could not import config '{}' (Is it on sys.path?): {}".format(DJANGO_CONF_MODULE, e))

for _setting in dir(_module):
    if _setting == _setting.upper():
        locals()[_setting] = getattr(_module, _setting)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*!%)j#u)nk*s+7!tm6uqw*l)q+q++b9wctsdic#hq3pp(_*&*7"

# 入口配置
ROOT_URLCONF = "apps.urls"
WSGI_APPLICATION = "apps.wsgi.application"

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# 平台错误码前缀
PLATFORM_CODE = 00

try:
    from config.celery_config import app  # noqa
except ImportError:
    pass
