global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'dashboard'

alerting:
 alertmanagers:
 - static_configs:
    - targets:
        - "alertmanager:9093"

rule_files:
  #- 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
# mac获取宿主机 ip 地址：ipconfig getifaddr en0
# 替换下面的 ip 地址
        #- targets: ['ip:5001']
#  - job_name: 'cadvisor'
#    static_configs:
#    - targets: ['ip:8899']
#  - job_name: 'node'
#    static_configs:
#    - targets: ['ip:9100']
  - job_name: pushgateway
    static_configs:
      - targets: ['x.x.x.x:9091']
        labels:
          instance: pushgateway
