# Generated by Django 3.2.25 on 2024-05-12 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestSystemConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.CharField(db_index=True, default="", max_length=32, null=True, verbose_name="创建者"),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("name", models.CharField(max_length=64, verbose_name="系统名称")),
                ("code", models.CharField(db_index=True, default="", max_length=64, verbose_name="API编码")),
                ("desc", models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="系统描述")),
                (
                    "owners",
                    models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="系统责任人"),
                ),
                (
                    "domain",
                    models.CharField(blank=True, default="", max_length=10000, null=True, verbose_name="系统域名"),
                ),
                ("headers", models.JSONField(blank=True, default=list, null=True, verbose_name="系统公共头部")),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "unique_together": {("code",)},
            },
        ),
        migrations.CreateModel(
            name="RequestApiConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.CharField(db_index=True, default="", max_length=32, null=True, verbose_name="创建者"),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("code", models.CharField(db_index=True, default="", max_length=64, verbose_name="API编码")),
                ("name", models.CharField(max_length=64, verbose_name="API名称")),
                ("path", models.CharField(max_length=1000, verbose_name="API路径")),
                (
                    "method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")], max_length=32, verbose_name="请求方法"
                    ),
                ),
                ("desc", models.CharField(default="", max_length=255, verbose_name="描述")),
                ("request_headers", models.JSONField(blank=True, default=list, null=True, verbose_name="headers参数")),
                ("request_params", models.JSONField(blank=True, default=list, null=True, verbose_name="query参数")),
                ("request_body", models.JSONField(blank=True, default=dict, null=True, verbose_name="body参数")),
                (
                    "system",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="系统",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="http_client.requestsystemconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "API配置",
                "verbose_name_plural": "API配置",
                "unique_together": {("code", "system")},
            },
        ),
    ]
