# Generated by Django 4.2.13 on 2024-06-01 14:59

import apps.account.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationlog",
            options={"ordering": ("-created_at",), "verbose_name": "操作日志", "verbose_name_plural": "操作日志"},
        ),
        migrations.AlterModelManagers(
            name="users",
            managers=[
                ("objects", apps.account.models.user.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="operationlog",
            name="request_id",
            field=models.CharField(max_length=32, null=True, verbose_name="请求唯一 ID"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="request_method",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="请求方式"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="request_path",
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="请求地址"),
        ),
    ]
