# Generated by Django 3.2.25 on 2024-05-09 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.CharField(db_index=True, default="", max_length=32, null=True, verbose_name="创建者"),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "value_type",
                    models.CharField(
                        max_length=64,
                        verbose_name="option对应类型",
                        choices=[
                            ("bool", "bool"),
                            ("string", "string"),
                            ("list", "list"),
                            ("dict", "dict"),
                            ("int", "int"),
                            ("datetime", "datetime"),
                            ("null", "null"),
                        ],
                    ),
                ),
                ("value", models.TextField(verbose_name="option配置内容")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="配置key")),
                ("description", models.TextField(blank=True, default="", null=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "全局配置信息",
                "verbose_name_plural": "全局配置信息",
                "db_table": "global_setting",
            },
        ),
    ]
