# Generated by Django 4.2.13 on 2024-05-30 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_conf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.CharField(db_index=True, default="", max_length=32, null=True, verbose_name="创建者"),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("label", models.CharField(blank=True, max_length=128, null=True, verbose_name="字典名称")),
                ("value", models.CharField(blank=True, max_length=255, null=True, verbose_name="字典编号")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TEXT", "文本"),
                            ("NUMBER", "数字"),
                            ("DATE", "日期"),
                            ("TIME", "时间"),
                            ("DATETIME", "日期时间"),
                            ("FILE", "文件"),
                            ("IMAGE", "图片"),
                        ],
                        default="TEXT",
                        max_length=32,
                        verbose_name="数据值类型",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=32, null=True, verbose_name="颜色")),
                ("is_value", models.BooleanField(default=False, verbose_name="是否为value值")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                ("sort", models.IntegerField(blank=True, default=1, null=True, verbose_name="显示排序")),
                ("remark", models.TextField(default="", verbose_name="备注")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sublist",
                        to="global_conf.dictionary",
                        verbose_name="父级",
                    ),
                ),
            ],
            options={
                "verbose_name": "字典表",
                "verbose_name_plural": "字典表",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.CharField(db_index=True, default="", max_length=32, null=True, verbose_name="创建者"),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=32, null=True, verbose_name="修改者"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("title", models.CharField(max_length=50, verbose_name="标题")),
                ("key", models.CharField(db_index=True, max_length=20, verbose_name="键")),
                ("value", models.JSONField(blank=True, max_length=100, null=True, verbose_name="值")),
                ("sort", models.IntegerField(blank=True, default=0, verbose_name="排序")),
                ("status", models.BooleanField(default=True, verbose_name="启用状态")),
                ("data_options", models.JSONField(blank=True, null=True, verbose_name="数据options")),
                (
                    "form_item_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TEXT", "文本"),
                            ("DATETIME", "日期时间"),
                            ("DATE", "日期"),
                            ("TIME", "时间"),
                            ("TEXTAREA", "富文本框"),
                            ("SELECT", "下拉列表"),
                            ("CHECKBOX", "复选框"),
                            ("RADIO", "单选框"),
                            ("IMAGE", "图片"),
                            ("FILE", "文件"),
                            ("SWITCH", "开关"),
                            ("NUMBER", "数字选择框"),
                            ("ARRAY", "ARRAY"),
                            ("IMAGES", "多个图片"),
                            ("FOREIGNKEY", "外键-多对一"),
                            ("MANYTOMANY", "外键-多对多"),
                        ],
                        default=0,
                        max_length=32,
                        verbose_name="表单类型",
                    ),
                ),
                ("rule", models.JSONField(blank=True, null=True, verbose_name="校验规则")),
                ("placeholder", models.CharField(blank=True, max_length=50, null=True, verbose_name="提示信息")),
                ("setting", models.JSONField(blank=True, null=True, verbose_name="配置")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="global_conf.systemconfig",
                        verbose_name="父级",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统配置表",
                "verbose_name_plural": "系统配置表",
                "unique_together": {("key", "parent_id")},
            },
        ),
    ]
