# Generated by Django 4.2.21 on 2025-05-17 13:39

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_conf', '0002_dictionary_systemconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FunctionController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='功能名称')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否开启')),
                (
                    'is_frozen',
                    models.BooleanField(
                        default=False, help_text='人工冻结此开关，将不受更新影响', verbose_name='是否冻结'
                    ),
                ),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                (
                    'parent',
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='global_conf.functioncontroller',
                        verbose_name='父功能',
                    ),
                ),
            ],
            options={
                'verbose_name': '功能控制器(FunctionController)',
                'verbose_name_plural': '功能控制器(FunctionController)',
            },
        ),
    ]
