# Generated by Django 4.2.21 on 2025-05-18 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTypePeriodicTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
                ),
                (
                    'created_by',
                    models.CharField(db_index=True, default='', max_length=32, null=True, verbose_name='创建者'),
                ),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                (
                    'updated_by',
                    models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='修改者'),
                ),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='周期任务名称')),
                (
                    'task_type',
                    models.CharField(
                        choices=[('remote', '远程 API 周期任务'), ('local', '本地函数周期任务')],
                        max_length=32,
                        verbose_name='任务类型',
                    ),
                ),
                ('is_frozen', models.BooleanField(default=False, verbose_name='是否冻结')),
                (
                    'task',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='django_celery_beat.periodictask',
                        verbose_name='celery 周期任务实例',
                    ),
                ),
            ],
            options={
                'verbose_name': '周期任务',
                'verbose_name_plural': '周期任务',
            },
        ),
    ]
