# Generated by Django 3.2.25 on 2024-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, verbose_name='关键字')),
                ('value', models.IntegerField(verbose_name='值')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('string', '字符串'),
                            ('hash', '哈希值'),
                            ('list', '列表'),
                            ('set', '集合'),
                            ('zset', '有序集合'),
                        ],
                        default='string',
                        max_length=32,
                        verbose_name='类型',
                    ),
                ),
                ('expire_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '数据存储',
                'verbose_name_plural': '数据存储',
            },
        ),
    ]
